[project]
name = 'Blockchain-Based-Specialized-Industrial-Equipment-Certification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.maintenance-history]
path = 'contracts/maintenance-history.clar'
clarity_version = 2
epoch = 2.5

[contracts.manufacturer-verification]
path = 'contracts/manufacturer-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.operator-training]
path = 'contracts/operator-training.clar'
clarity_version = 2
epoch = 2.5

[contracts.testing-certification]
path = 'contracts/testing-certification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
